### ISSUE TITLE
Does rotor support http messaging between actors?

### ISSUE THREAD

**Issue by zpxp** [basiliscos/cpp-rotor#28]
Can we scale programs using `rotor` across multiple servers and have actors able to find and communicate with each other? This is similar functionality to other actor frameworks, such as Orleans.

**Comment by basiliscos** [comment]
At the moment, there is no such a possibility, and that's why:  1) the wire-format should be defined by user, 2) most of messages should be defined by user (i.e. http), 3) it should transport/event-loop agnostic. To support that level of customization, there is need of `reflection` in C++ language, but it not shipped yet.

In theory, some primitive it can implemented by user, i.e. 

```cpp
struct service_proxy: r::actor_base {

void on_message(... &message) {
  ... // serialize and send it over the wire, i.e. as http
}
};

struct receiver: r::actor_base {

void on_wire_data(std::string data) {
   // deserialize it as message and send further
    send<service_address>(...);
}
};

```

That's way it is possible to do like `send<proxy_addess>(...)` from `hostA`, deserialize it on `hostB` via `receiver` and forward to the `service_address`.  However, a lot of things have to be done manually, and, the most significant drawback, that there is **no infrastructural support**, which should be anyway implemented by user.

**Comment by zpxp** [comment]
Okay thanks.
